# Generated by Django 4.0.5 on 2022-06-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0002_airport_alter_vols_destination_alter_vols_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('vols', models.ManyToManyField(blank=True, related_name='passengers', to='vols.vols')),
            ],
        ),
    ]
